<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="mario" tilewidth="16" tileheight="16" tilecount="192" columns="16">
 <image source="mario.png" width="256" height="192"/>
 <tile id="0" type="right-big-mario-upper"/>
 <tile id="1" type="right-big-mario-upper"/>
 <tile id="2" type="right-big-mario-upper"/>
 <tile id="3" type="right-big-mario-upper"/>
 <tile id="4" type="right-big-mario-upper"/>
 <tile id="5" type="right-big-mario-upper"/>
 <tile id="6" type="right-big-mario-upper"/>
 <tile id="7" type="right-big-mario-upper"/>
 <tile id="8" type="right-big-mario-upper"/>
 <tile id="9" type="right-big-mario-upper"/>
 <tile id="10" type="right-big-mario-upper"/>
 <tile id="11" type="right-big-mario-upper"/>
 <tile id="12" type="right-big-mario-upper"/>
 <tile id="13" type="right-big-mario-upper"/>
 <tile id="14" type="right-big-mario-upper"/>
 <tile id="15" type="right-big-mario-upper"/>
 <tile id="16" type="right-big-mario-lower"/>
 <tile id="17" type="right-big-mario-lower"/>
 <tile id="18" type="right-big-mario-lower"/>
 <tile id="19" type="right-big-mario-lower"/>
 <tile id="20" type="right-big-mario-lower"/>
 <tile id="21" type="right-big-mario-lower"/>
 <tile id="22" type="right-big-mario-lower"/>
 <tile id="23" type="right-big-mario-lower"/>
 <tile id="24" type="right-big-mario-lower"/>
 <tile id="25" type="right-big-mario-lower"/>
 <tile id="26" type="right-big-mario-lower"/>
 <tile id="27" type="right-big-mario-lower"/>
 <tile id="28" type="right-big-mario-lower"/>
 <tile id="29" type="right-big-mario-lower"/>
 <tile id="30" type="right-big-mario-lower"/>
 <tile id="31" type="right-big-mario-lower"/>
 <tile id="32" type="right-small-mario"/>
 <tile id="33" type="right-small-mario"/>
 <tile id="34" type="right-small-mario"/>
 <tile id="35" type="right-small-mario"/>
 <tile id="36" type="right-small-mario"/>
 <tile id="37" type="right-small-mario"/>
 <tile id="38" type="right-small-mario"/>
 <tile id="39" type="right-small-mario"/>
 <tile id="40" type="right-small-mario"/>
 <tile id="41" type="right-small-mario"/>
 <tile id="42" type="right-small-mario"/>
 <tile id="43" type="right-small-mario"/>
 <tile id="44" type="right-small-mario"/>
 <tile id="45" type="right-small-mario"/>
 <tile id="46" type="blank"/>
 <tile id="47" type="blank"/>
 <tile id="48" type="right-bw-mario-upper"/>
 <tile id="49" type="right-bw-mario-upper"/>
 <tile id="50" type="right-bw-mario-upper"/>
 <tile id="51" type="right-bw-mario-upper"/>
 <tile id="52" type="right-bw-mario-upper"/>
 <tile id="53" type="right-bw-mario-upper"/>
 <tile id="54" type="right-bw-mario-upper"/>
 <tile id="55" type="right-bw-mario-upper"/>
 <tile id="56" type="right-bw-mario-upper"/>
 <tile id="57" type="right-bw-mario-upper"/>
 <tile id="58" type="right-bw-mario-upper"/>
 <tile id="59" type="right-bw-mario-upper"/>
 <tile id="60" type="right-bw-mario-upper"/>
 <tile id="61" type="right-bw-mario-upper"/>
 <tile id="62" type="right-bw-mario-upper"/>
 <tile id="63" type="right-bw-mario-upper"/>
 <tile id="64" type="right-bw-mario-lower"/>
 <tile id="65" type="right-bw-mario-lower"/>
 <tile id="66" type="right-bw-mario-lower"/>
 <tile id="67" type="right-bw-mario-lower"/>
 <tile id="68" type="right-bw-mario-lower"/>
 <tile id="69" type="right-bw-mario-lower"/>
 <tile id="70" type="right-bw-mario-lower"/>
 <tile id="71" type="right-bw-mario-lower"/>
 <tile id="72" type="right-bw-mario-lower"/>
 <tile id="73" type="right-bw-mario-lower"/>
 <tile id="74" type="right-bw-mario-lower"/>
 <tile id="75" type="right-bw-mario-lower"/>
 <tile id="76" type="right-bw-mario-lower"/>
 <tile id="77" type="right-bw-mario-lower"/>
 <tile id="78" type="right-bw-mario-lower"/>
 <tile id="79" type="right-bw-mario-lower"/>
 <tile id="80" type="right-small-mario-wb"/>
 <tile id="81" type="right-small-mario-wb"/>
 <tile id="82" type="right-small-mario-wb"/>
 <tile id="83" type="right-small-mario-wb"/>
 <tile id="84" type="right-small-mario-wb"/>
 <tile id="85" type="right-small-mario-wb"/>
 <tile id="86" type="right-small-mario-wb"/>
 <tile id="87" type="right-small-mario-wb"/>
 <tile id="88" type="right-small-mario-wb"/>
 <tile id="89" type="right-small-mario-wb"/>
 <tile id="90" type="right-small-mario-wb"/>
 <tile id="91" type="right-small-mario-wb"/>
 <tile id="92" type="right-small-mario-wb"/>
 <tile id="93" type="right-small-mario-wb"/>
 <tile id="96" type="blank"/>
 <tile id="97" type="blank"/>
 <tile id="98" type="blank"/>
 <tile id="99" type="blank"/>
 <tile id="100" type="blank"/>
 <tile id="101" type="blank"/>
 <tile id="102" type="blank"/>
 <tile id="103" type="blank"/>
 <tile id="104" type="blank"/>
 <tile id="105" type="blank"/>
 <tile id="106" type="blank"/>
 <tile id="107" type="blank"/>
 <tile id="108" type="blank"/>
 <tile id="109" type="blank"/>
 <tile id="110" type="blank"/>
 <tile id="111" type="blank"/>
 <tile id="112" type="blank"/>
 <tile id="113" type="blank"/>
 <tile id="114" type="blank"/>
 <tile id="115" type="blank"/>
 <tile id="116" type="blank"/>
 <tile id="117" type="blank"/>
 <tile id="118" type="blank"/>
 <tile id="119" type="blank"/>
 <tile id="120" type="blank"/>
 <tile id="121" type="blank"/>
 <tile id="122" type="blank"/>
 <tile id="123" type="blank"/>
 <tile id="124" type="blank"/>
 <tile id="125" type="blank"/>
 <tile id="126" type="blank"/>
 <tile id="127" type="blank"/>
 <tile id="128" type="blank"/>
 <tile id="129" type="blank"/>
 <tile id="130" type="blank"/>
 <tile id="131" type="blank"/>
 <tile id="132" type="blank"/>
 <tile id="133" type="blank"/>
 <tile id="134" type="blank"/>
 <tile id="135" type="blank"/>
 <tile id="136" type="blank"/>
 <tile id="137" type="blank"/>
 <tile id="138" type="blank"/>
 <tile id="139" type="blank"/>
 <tile id="140" type="blank"/>
 <tile id="141" type="blank"/>
 <tile id="142" type="blank"/>
 <tile id="143" type="blank"/>
 <tile id="144" type="blank"/>
 <tile id="145" type="blank"/>
 <tile id="146" type="blank"/>
 <tile id="147" type="blank"/>
 <tile id="148" type="blank"/>
 <tile id="149" type="blank"/>
 <tile id="150" type="blank"/>
 <tile id="151" type="blank"/>
 <tile id="152" type="blank"/>
 <tile id="153" type="blank"/>
 <tile id="154" type="blank"/>
 <tile id="155" type="blank"/>
 <tile id="156" type="blank"/>
 <tile id="157" type="blank"/>
 <tile id="158" type="blank"/>
 <tile id="159" type="blank"/>
 <tile id="160" type="blank"/>
 <tile id="161" type="blank"/>
 <tile id="162" type="blank"/>
 <tile id="163" type="blank"/>
 <tile id="164" type="blank"/>
 <tile id="165" type="blank"/>
 <tile id="166" type="blank"/>
 <tile id="167" type="blank"/>
 <tile id="168" type="blank"/>
 <tile id="169" type="blank"/>
 <tile id="170" type="blank"/>
 <tile id="171" type="blank"/>
 <tile id="172" type="blank"/>
 <tile id="173" type="blank"/>
 <tile id="174" type="blank"/>
 <tile id="175" type="blank"/>
 <tile id="176" type="blank"/>
 <tile id="177" type="blank"/>
 <tile id="178" type="blank"/>
 <tile id="179" type="blank"/>
 <tile id="180" type="blank"/>
 <tile id="181" type="blank"/>
 <tile id="182" type="blank"/>
 <tile id="183" type="blank"/>
 <tile id="184" type="blank"/>
 <tile id="185" type="blank"/>
 <tile id="186" type="blank"/>
 <tile id="187" type="blank"/>
 <tile id="188" type="blank"/>
 <tile id="189" type="blank"/>
 <tile id="190" type="blank"/>
 <tile id="191" type="blank"/>
</tileset>
